name: Flask App Tests

# add trigger
on:
  pull_request:
    branches:
      - main

# define jobs
jobs:
  test:
    runs-on: [ windows-latest ]
    defaults:
      run:
        working-directory: ./app/

    strategy:
      matrix:
        python-version: ['3.10']

    env:
      MODE: ${{ secrets.MODE }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      
      - name: Test App Code
        run: python ./main_test.py

    
      
